### ISSUE TITLE
brewed apache24 compatibility

### ISSUE THREAD

**Issue by ptica** [virtualhost/virtualhost.sh#78]
hi and thank you for a super useful utility!

I was forced to switch to brewed apache24, as the brewed php 5.6.30 no longer supports the build-in apache

my virtualhosts in /private/etc/apache2/virtualhosts are not being honored as 
brewed apache24 reads the configuration from /usr/local/etc/apache2/2.4

I've added a line of 
```
Include /private/etc/apache2/virtualhosts
```

to `/usr/local/etc/apache2/2.4/httpd.conf` 've and restarted apache using `sudo apachectl restart`

but I'm not sure whether this is the preferred solution,
a detection of brewed 2.4 would probably simplify life to a lot of osx folks :)

**Comment by star-szr** [comment]
@ptica thanks for the issue! I'm not sure about adding detection (have to think about that some more, because users might have reasons to run both at once and probably other reasons). If you're using homebrewed Apache you can create `~/.virtualhost.sh.conf` with something like this (for Homebrewed Apache 2.4.x anyway):

```
APACHECTL=/usr/local/bin/apachectl
APACHE_CONFIG=/usr/local/etc/apache2/2.4
```

I'm using that on one of my machines and it works well.

**Comment by star-szr** [comment]
By the way, docs on the config variables are linked below but potentially this could be in an FAQ or something.

https://github.com/virtualhost/virtualhost.sh/wiki/Configuration
